name: Python CI

on:
  push:
    branches: [master]
  schedule:
  - cron: "*/5 * * * *"

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
    - name: Printing message
      run: echo "Run every 5 mns"
  
  custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read custom actions
        id: random
        uses: ./.github/actions/custom-action
        with:
          say-hello: "Sivaprakash"

      - run: |
          echo $RANDOM_NR
          if [ $RANDOM_NR -gt 100 ]
          then
            echo "Im big enough"
          fi
        shell: bash
        env:
          RANDOM_NR: ${{ steps.random.outputs.random-number }}
